{% set version = "0.2.1" %}

package:
  name: woops
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/woops/woops-{{ version }}.tar.gz
  sha256: f95dee22e055b61980209fdf481f33e743e02d5ef135853c9089d0061370f94a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - woops
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/woops/
  summary: Handle and manage Python errors with ease
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
